/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ogre-draco.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={2}>
        <mesh geometry={nodes.ogre.geometry} material={materials.ogreMesh} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      </group>
    </group>
  )
}

useGLTF.preload('/ogre-draco.gltf')
